#!/bin/bash
JOIN_TOKEN=exwly2.92xy610d0zt0h
JOIN_CERT_HASH=af7ffe8b6329deb282b56e6fc80d83b36433abaa52cc2763fbde3ed26b9d0b73

cat <<EOF > kubeadm-join.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.99.101:6443
    token: ${JOIN_TOKEN}
    caCertHashes:
    - sha256:${JOIN_CERT_HASH}
EOF

# verify whether variables are substituted properly 
cat kubeadm-join.yaml
sudo kubeadm join --config kubeadm-join.yaml
